source $HOME/.config/nvim/conf/plugins.vim       " plugin manager
source $HOME/.config/nvim/conf/main.vim          " main key mappings,history,...
source $HOME/.config/nvim/conf/look.vim          " basic ui, colors, fonts,...
source $HOME/.config/nvim/conf/ide.vim           " general IDE configs
source $HOME/.config/nvim/conf/edit.vim          " basic text editing settings
source $HOME/.config/nvim/conf/nav.vim           " movement in file, windows, tabs, ...
"source $HOME/.config/nvim/conf/lang/python.vim  " python
source $HOME/.config/nvim/conf/lang/configf.vim  " config files
source $HOME/.config/nvim/conf/lang/dataf.vim    " data files
